[project]
name = "cat-flap"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "tensorflow",
    "ipykernel",
    "pyyaml",
    "scikit-learn",
    "matplotlib",
    "pandas"
]
