[project]
name = "shared"
version = "0.1.0"
description = "Shared code for cat flap project"
requires-python = ">=3.13"
dependencies = [
    "pyzmq",
    "Pillow",
    "numpy",
]

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"
