name: Build and publish movement-detector service image

on:
  push:
    branches:
      - master
    paths:
      - "*"
      - "shared/**"
      - "movement-detector-service/**"
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      - name: Build movement-detector service
        uses: ./.github/actions/build-service
        with:
          service-name: movement-detector-service
          dockerhub-username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
