name: Build and publish servo service image

on:
  push:
    branches:
      - master
    paths:
      - "*"
      - "shared/**"
      - "servo-service/**"
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Build servo service
        uses: ./.github/actions/build-service
        with:
          stervice-name: servo-service
          dockerhub-username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
